### ISSUE TITLE
RPC issue on test net using Account and Transaction:push

### ISSUE THREAD

**Issue by ziptied** [ProtonProtocol/proton-cli#20]
seeing the following response when interacting only on testnet, main net works fine
`Error
    at new RpcStatusError (/opt/homebrew/lib/node_modules/@proton/cli/node_modules/@eoscafe/light-api/dist/src/rpcerror.js:53:28)
    at JsonRpc.<anonymous> (/opt/homebrew/lib/node_modules/@proton/cli/node_modules/@eoscafe/light-api/dist/src/jsonrpc.js:156:35)
    at step (/opt/homebrew/lib/node_modules/@proton/cli/node_modules/@eoscafe/light-api/dist/src/jsonrpc.js:43:23)
    at Object.next (/opt/homebrew/lib/node_modules/@proton/cli/node_modules/@eoscafe/light-api/dist/src/jsonrpc.js:24:53)
    at fulfilled (/opt/homebrew/lib/node_modules/@proton/cli/node_modules/@eoscafe/light-api/dist/src/jsonrpc.js:15:58)`

CLI version 0.1.70 & 0.1.76
Node v18.8.0
Checked the following Testnet Nodes

- https://protontestnet.ledgerwise.io
- https://proton-testnet.eosphere.io
- https://test.proton.eosusa.io
- https://proton.greymass.com
- https://api.eosvenezuela.io
- https://mainnet.eosamsterdam.net
- https://bp1.protonnz.com

Affected Commands:

- proton account 
- proton account {account} -t
- proton transaction:push

**Comment by ziptied** [comment]
Solved on the chain side, no issue with cli.
